name = "darkgamerroblox/pancakes"
version = "1.0.0"
description = "High-performance binary serialization library for Roblox"
license = "MIT"
authors = ["DarkGamer"]
repository = "https://github.com/darkgamerroblox/Pancakes"

includes = [
	"pesde.toml",
	"README.md",
	"LICENSE",
	"src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"
