[package]
name = "darkgamer/pancakes"
description = "High-performance binary serialization library for Roblox"
version = "1.0.0"
license = "MIT"
authors = ["DarkGamer"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

repository = "https://github.com/DarkGamerRoblox/Pancakes"
homepage = "https://DarkGamerRoblox.github.io/Pancakes/"

exclude = ["**"]

include = [
	"src",
	"src/*",
	"default.project.json",
	"wally.toml",
	"LICENSE",
	"README.md",
]

[dependencies]
