[package]
name = "darkgamerroblox/pancakes"
description = "High-performance binary serialization for Roblox Luau"
version = "1.0.0"
license = "MIT"
authors = ["DarkGamer"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

repository = "https://github.com/DarkGamerRoblox/Pancakes"
homepage = "https://darkgamerroblox.github.io/Pancakes/"

exclude = ["**"]

include = [
	"src",
	"src/**",
	"default.project.json",
	"README.md",
	"LICENSE",
	"wally.toml",
]

[dependencies]
